### ISSUE TITLE
经常会出现这个BUG，需要重新clean一下工程。然后rebuilt才行跑的通。请问一下如何解决。项目快要上线了，如果线上存在这个问题的话。那么问题就大了

### ISSUE THREAD

**Issue by weiningpeng** [PrototypeZ/AppJoint#25]
java.lang.AbstractMethodError: abstract method "void com.tgnet.router.IChatService.launchToChat(long, java.lang.String, java.lang.String, java.lang.String, long, boolean)"
        at app.tgnet.com.walktrace.fragment.IndexWalkTraceFragment$onViewCreated$1.onClickMessage(IndexWalkTraceFragment.kt:119)
        at app.tgnet.com.walktrace.adapter.WalkTraceDetailAdapter$ViewHolder$setOtherWalkTraceInfo$$inlined$run$lambda$2.onClick(WalkTraceDetailAdapter.kt:183)
        at android.view.View.performClick(View.java:6291)
        at android.view.View$PerformClick.run(View.java:24931)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by PrototypeZ** [comment]
您加一下我微信好吗 zjnb1114

**Comment by PrototypeZ** [comment]
目前推测与开发时开启Instant run有关，应该是个只有可能在开发阶段遇到的问题。正式发布版本全量编译应该不存在这个问题

**Comment by PrototypeZ** [comment]
no further imformation closing
