### ISSUE TITLE
service返回null，帮忙想想可能是什么低级错误？

### ISSUE THREAD

**Issue by helloworld10010** [PrototypeZ/AppJoint#40]
完全按照readme来的。。
一个字一个字对了的啊。
demo模块：app,module1,base
项目build.gradle，app build.gradle   classpath...加了，apply加了，implement每个都加了，app依赖base,module1依赖base,base里写接口，module1实现，加注解，app里getservice。 null...

`2020-09-24 13:51:14.653 30498-30498/com.example.componentizationpractice E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.componentizationpractice, PID: 30498
    java.lang.NullPointerException: Attempt to invoke interface method 'void com.example.base.Module1Service.startActivityOfModule1(android.content.Context)' on a null object reference
        at com.example.componentizationpractice.MainActivity$onCreate$1.onClick(MainActivity.kt:18)
        at android.view.View.performClick(View.java:6608)
        at android.view.View.performClickInternal(View.java:6585)
        at android.view.View.access$3100(View.java:785)
        at android.view.View$PerformClick.run(View.java:25921)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6878)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)`

**Comment by helloworld10010** [comment]
注意目标模块是否参与了编译
